name: Release

on:
  workflow_run:
    workflows: [ "Version" ]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    runs-on: windows-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      # When testing or working with forks, electron builder will try and publish to the main repo, not the fork.
      # This allows it to publish to the forked repo for testing
      - name: Replace package.json repository
        shell: bash
        run: |
          contents="$(jq --arg repo $GITHUB_SERVER_URL/$GITHUB_REPOSITORY '.repository = $repo' package.json)"
          echo $contents > package.json

      - name: Build app
        run: npm run build -- --publish always
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
