name: Version

on:
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  version-bump:
    runs-on: ubuntu-latest
    # Prevent the versioning getting stuck in a loop when it pushes back to the main branch
    if: github.actor != 'UltimateSkyrimGitHub'

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure CI Git User
        run: |
          git config user.name 'UltimateSkyrimGitHubCI'
          git config user.email 'ultimateskyrimgithub@gmail.com'

      - name: publish changes
        run: |
          git fetch
          git checkout main
          touch test.example
          git add .
          git commit -m "testing updating main"
          git push origin main
