name: Version

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  version-bump:
    runs-on: ubuntu-latest
    # Prevent the versioning getting stuck in a loop when it pushes back to the main branch
    if: "!contains(toJSON(github.event.commits.*.message), 'chore(release)')"

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - uses: fregante/setup-git-user@v1

      - name: Use Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'

      - name: bump version
        run: npx standard-version --no-verify

      # Inspired by https://github.com/CasperWA/push-protected but unable to get it working with this repository.
      # Instead, we just wait a set amount of time and hope the status checks complete.
      # Eventually this will need revisiting to ensure status checks pass before continuing
      - name: publish changes
        run: |
          TEMP_BRANCH=release-temp/$(cat /proc/sys/kernel/random/uuid)
          git checkout -b $TEMP_BRANCH
          git push -f origin $TEMP_BRANCH

          sleep 200

          git checkout main
          git reset --hard $TEMP_BRANCH
          git push origin main
          git push --tags
          git push -d origin $TEMP_BRANCH
