name: Version

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: bump version
        run: npx standard-version --no-verify

      - name: publish changes
        run: git push --follow-tags
